# isa3d-web-app/nginx.conf
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Si el archivo no existe, sirve index.html (para Angular Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: comprime assets
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}